services:
#    code_produdo.example:
#        class: Code\ProdudoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  code_produdo.manager.produto :
      class: Code\ProdudoBundle\Manager\ProdutoManager
      arguments:
        - "@doctrine.orm.entity_manager"
