code_category:
    resource: "@CodeCategoryBundle/Controller/"
    type:     annotation
    prefix:   /

code_code_car:
    resource: "@CodeCodeCarBundle/Controller/"
    type:     annotation
    prefix:   /cars/

code_produdo:
    resource: "@CodeProdudoBundle/Controller/"
    type:     annotation
    prefix:   /produtos/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation