services:
#    code_code_car.example:
#        class: Code\CodeCarBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  code_code_car.manager.fabricante:
      class: Code\CodeCarBundle\Manager\FabricanteManager
      arguments:
        - "@doctrine.orm.entity_manager"
